# 4. Selecting Subsets of Data from DataFrames with just the brackets

### Objectives

+ Read in a dataset with `read_csv` and set the index with the `index_col` parameter
+ Know the three indexers `[ ]`, `.loc`, and `.iloc` are used to select subsets of data
+ The primary purpose of *just the brackets* is to select columns of a DataFrame

### Prepare for this lesson by...

+ Read [Indexing and Selecting](http://pandas.pydata.org/pandas-docs/stable/indexing.html) - **up to but not including Selection By Callable**

# Selecting Subsets of Data
One of the most common tasks during a data analysis is to select subsets of the dataset. In Pandas, this means selecting particular rows and/or columns from our DataFrame (or Series).

## Examples of Selections of Subsets of Data
The following will show images of different types of subset selection that are possible. We will first highlight the values we want and then show the corresponding DataFrame after the completed selection.

### Selection of columns

![][2]

Resulting DataFrame:

![][3]

### Selection of rows

![][4]

Resulting DataFrame:

![][5]

### Selection of rows and columns

![][6]

Resulting DataFrame:

![][7]

[1]: images/sample_df.png
[2]: images/just_cols.png
[3]: images/just_cols2.png
[4]: images/just_rows.png
[5]: images/just_rows2.png
[6]: images/rows_cols.png
[7]: images/rows_cols2.png

# Pandas dual references: by label and by integer location
As previously mentioned, the index of each DataFrame provides a label to reference each individual row. Similarly the columns provide a label to reference each column.

But, what hasn't been mentioned, is that each row and column may be referenced by an integer as well. I call this **integer location**. The integer location begins at 0 and ends at n-1 for each row and column. Take a look above at our sample DataFrame one more time.

The rows with labels **`Aaron`** and **`Dean`** can also be referenced by their respective integer locations 2 and 4. Similarly, the columns **`color`**, **`age`**, and **`height`** can be referenced by their integer locations 1, 3, and 4.

The documentation refers to integer location as **position**. I don't particularly like this terminology as it's not as explicit as integer location. The key term here is INTEGER.

# What's the difference between indexing and selecting subsets of data?
The documentation uses the term **indexing** frequently. This term is essentially just a one-word phrase to say **subset selection**. I prefer the term subset selection as, again, it is more descriptive of what is actually happening. Indexing is also the term used in the official Python documentation (for selecting subsets of lists or strings for example).

# The three indexers `[ ]`, `.loc`, `.iloc`
Pandas provides three **indexers** to select subsets of data. An indexer is a term for one of  `[ ]`, `.loc`, or `.iloc` and what makes the subset selection.

We will go in-depth on how to make selections with each of these indexers. Each indexer has different rules for how it works. All our selections will look similar to the following, except they will have something placed within the brackets.

```
>>> df[]
>>> df.loc[]
>>> df.iloc[]
```
### Terminology
When the brackets are placed directly after the DataFrame, the term **just the brackets** will be used to differentiate from the brackets after **`.loc`** and **`.iloc`**.

# Begin with *just the brackets*
As we saw in the last notebook, just the brackets are used to select a single column as a Series. We place the column name inside the brackets to return the Series.

In [1]:
import pandas as pd
df = pd.read_csv('../data/sample_data.csv')

In [2]:
df['color']

0     blue
1    green
2      red
3    white
4     gray
5    black
6      red
Name: color, dtype: object

## Select Multiple Columns with a List
You can select multiple columns by placing them in a list inside of just the brackets. Notice that a DataFrame and NOT a Series is returned:

In [3]:
df[['color', 'age', 'score']]

   color  age  score
0   blue   30    4.6
1  green    2    8.3
2    red   12    9.0
3  white    4    3.3
4   gray   32    1.8
5  black   33    9.5
6    red   69    2.2

### You must use an inner set of brackets
You might be tempted to do the following which will NOT work. You must pass the columns names as a **list** - remember that a list is defined by a set of brackets.

In [ ]:
# NO! An exception is raised

df['color', 'age', 'score']

# Use two lines of code to select multiple columns
To help ease the process of making subset selection, I recommend using intermediate variables. In this instance, we can assign the columns we would like to select to a list and then pass this list to the brackets.

In [5]:
cols = ['color', 'age', 'score']
df[cols]

   color  age  score
0   blue   30    4.6
1  green    2    8.3
2    red   12    9.0
3  white    4    3.3
4   gray   32    1.8
5  black   33    9.5
6    red   69    2.2

### Column order does not matter
You can create new DataFrames in any column order you wish - it need not match the original column order

In [6]:
cols = ['height', 'age']
df[cols]

   height  age
0     165   30
1      70    2
2     120   12
3      80    4
4     180   32
5     172   33
6     150   69

# The Default index
When we first read in our DataFrame, we specified the first column from the CSV file to be our index. If you don't specify an index, then Pandas will create one for you as the integers from 0 to n-1.

Let's read in the movie dataset without setting an index.

In [7]:
movie = pd.read_csv('../data/movie.csv')
movie.head()

,title,year,color,content_rating,duration,director_name,director_fb,actor1,actor1_fb,actor2,...,actor3_fb,gross,genres,num_reviews,num_voted_users,plot_keywords,language,country,budget,imdb_score
0,Avatar,2009.0,Color,PG-13,178.0,James Cameron,0.0,CCH Pounder,1000.0,Joel David Moore,...,855.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,723.0,886204,avatar|future|marine|native|paraplegic,English,USA,237000000.0,7.9
1,Pirates of the Caribbean: At World's End,2007.0,Color,PG-13,169.0,Gore Verbinski,563.0,Johnny Depp,40000.0,Orlando Bloom,...,1000.0,309404152.0,Action|Adventure|Fantasy,302.0,471220,goddess|marriage ceremony|marriage proposal|pi...,English,USA,300000000.0,7.1
2,Spectre,2015.0,Color,PG-13,148.0,Sam Mendes,0.0,Christoph Waltz,11000.0,Rory Kinnear,...,161.0,200074175.0,Action|Adventure|Thriller,602.0,275868,bomb|espionage|sequel|spy|terrorist,English,UK,245000000.0,6.8
3,The Dark Knight Rises,2012.0,Color,PG-13,164.0,Christopher Nolan,22000.0,Tom Hardy,27000.0,Christian Bale,...,23000.0,448130642.0,Action|Thriller,813.0,1144337,deception|imprisonment|lawlessness|police offi...,English,USA,250000000.0,8.5
4,Star Wars: Episode VII - The Force Awakens,NaN,NaN,NaN,NaN,Doug Walker,131.0,Doug Walker,131.0,Rob Walker,...,NaN,NaN,Documentary,NaN,8,NaN,NaN,NaN,NaN,7.1

### Notice the integers in the index
These integers are the default index labels for each of the rows. Let's examine the underlying index object.

In [8]:
movie.index

RangeIndex(start=0, stop=4916, step=1)

In [9]:
type(movie.index)

pandas.core.indexes.range.RangeIndex

### A RangeIndex
Pandas has many different types of index objects. A **`RangeIndex`** is similar to pure Python **`range`** object. The integers are not actually stored in memory and only accessed when requested.

# Setting a Meaningful Index
The **`RangeIndex`** does not provide us with much meaning as a labels for the rows. 

### Setting an index with `read_csv`
At the top of the notebook, we set our index to be the first column with the **`read_csv`** function by setting the **`index_col`** parameter equal to 0. You can use either integers or the column name to set the index like this.

### Re-read movie dataset with movie title as index
There's a column in the movie dataset named **`title`**. Let's re-read in the data with it as the index.

Notice that now the titles of each movie serve as the label for each row. Also notice that the word **title** appears directly above the index. This is a bit confusing - **title** is NOT a column name, but rather the **name of the index**.

In [10]:
movie = pd.read_csv('../data/movie.csv', index_col='title')
movie.head()

,year,color,content_rating,duration,director_name,director_fb,actor1,actor1_fb,actor2,actor2_fb,...,actor3_fb,gross,genres,num_reviews,num_voted_users,plot_keywords,language,country,budget,imdb_score
title,,,,,,,,,,,,,,,,,,,,,
Avatar,2009.0,Color,PG-13,178.0,James Cameron,0.0,CCH Pounder,1000.0,Joel David Moore,936.0,...,855.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,723.0,886204,avatar|future|marine|native|paraplegic,English,USA,237000000.0,7.9
Pirates of the Caribbean: At World's End,2007.0,Color,PG-13,169.0,Gore Verbinski,563.0,Johnny Depp,40000.0,Orlando Bloom,5000.0,...,1000.0,309404152.0,Action|Adventure|Fantasy,302.0,471220,goddess|marriage ceremony|marriage proposal|pi...,English,USA,300000000.0,7.1
Spectre,2015.0,Color,PG-13,148.0,Sam Mendes,0.0,Christoph Waltz,11000.0,Rory Kinnear,393.0,...,161.0,200074175.0,Action|Adventure|Thriller,602.0,275868,bomb|espionage|sequel|spy|terrorist,English,UK,245000000.0,6.8
The Dark Knight Rises,2012.0,Color,PG-13,164.0,Christopher Nolan,22000.0,Tom Hardy,27000.0,Christian Bale,23000.0,...,23000.0,448130642.0,Action|Thriller,813.0,1144337,deception|imprisonment|lawlessness|police offi...,English,USA,250000000.0,8.5
Star Wars: Episode VII - The Force Awakens,NaN,NaN,NaN,NaN,Doug Walker,131.0,Doug Walker,131.0,Rob Walker,12.0,...,NaN,NaN,Documentary,NaN,8,NaN,NaN,NaN,NaN,7.1

#### Extract new index and its type
We now have a 'plain' **`Index`** object.

In [11]:
movie.index

Index(['Avatar', 'Pirates of the Caribbean: At World's End', 'Spectre',
       'The Dark Knight Rises', 'Star Wars: Episode VII - The Force Awakens',
       'John Carter', 'Spider-Man 3', 'Tangled', 'Avengers: Age of Ultron',
       'Harry Potter and the Half-Blood Prince',
       ...
       'Primer', 'Cavite', 'El Mariachi', 'The Mongol King', 'Newlyweds',
       'Signed Sealed Delivered', 'The Following', 'A Plague So Pleasant',
       'Shanghai Calling', 'My Date with Drew'],
      dtype='object', name='title', length=4916)

In [12]:
type(movie.index)

pandas.core.indexes.base.Index

### Choosing a good index
First, its not necessary to choose an index for your DataFrames. You can do all your analysis with just the default **`RangeIndex`**. Setting a column to be an index can help you identify the rows such as we did with the movie titles above.

I suggest choosing columns that are both **unique** and **descriptive**. Although uniqueness is not enforced, it helps to identify one particular row.

## Setting the index after read
It is possible to set the index after reading the data with the **`set_index`** method. Simply pass it the name of the column you would like to use as the index. Make sure to re-assign the DataFrame after calling the method.

In [13]:
movie = pd.read_csv('../data/movie.csv')  # read in data without setting index
movie = movie.set_index('title')
movie.head()

,year,color,content_rating,duration,director_name,director_fb,actor1,actor1_fb,actor2,actor2_fb,...,actor3_fb,gross,genres,num_reviews,num_voted_users,plot_keywords,language,country,budget,imdb_score
title,,,,,,,,,,,,,,,,,,,,,
Avatar,2009.0,Color,PG-13,178.0,James Cameron,0.0,CCH Pounder,1000.0,Joel David Moore,936.0,...,855.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,723.0,886204,avatar|future|marine|native|paraplegic,English,USA,237000000.0,7.9
Pirates of the Caribbean: At World's End,2007.0,Color,PG-13,169.0,Gore Verbinski,563.0,Johnny Depp,40000.0,Orlando Bloom,5000.0,...,1000.0,309404152.0,Action|Adventure|Fantasy,302.0,471220,goddess|marriage ceremony|marriage proposal|pi...,English,USA,300000000.0,7.1
Spectre,2015.0,Color,PG-13,148.0,Sam Mendes,0.0,Christoph Waltz,11000.0,Rory Kinnear,393.0,...,161.0,200074175.0,Action|Adventure|Thriller,602.0,275868,bomb|espionage|sequel|spy|terrorist,English,UK,245000000.0,6.8
The Dark Knight Rises,2012.0,Color,PG-13,164.0,Christopher Nolan,22000.0,Tom Hardy,27000.0,Christian Bale,23000.0,...,23000.0,448130642.0,Action|Thriller,813.0,1144337,deception|imprisonment|lawlessness|police offi...,English,USA,250000000.0,8.5
Star Wars: Episode VII - The Force Awakens,NaN,NaN,NaN,NaN,Doug Walker,131.0,Doug Walker,131.0,Rob Walker,12.0,...,NaN,NaN,Documentary,NaN,8,NaN,NaN,NaN,NaN,7.1

# Changing Display Options
Pandas gives you the ability to change how the output on your screen is displayed. For instance, the default number of columns displayed for a DataFrame is 20 (and 60 for rows), meaning that if your DataFrame has more than 20 rows then only the first and last 10 rows will be shown on the screen.

The display options all come after `pd.options.display.<option_name>` where **`<option_name>`** is one of the following:

In [14]:
dir(pd.options.display)

['chop_threshold',
 'colheader_justify',
 'column_space',
 'date_dayfirst',
 'date_yearfirst',
 'encoding',
 'expand_frame_repr',
 'float_format',
 'html',
 'large_repr',
 'latex',
 'max_categories',
 'max_columns',
 'max_colwidth',
 'max_info_columns',
 'max_info_rows',
 'max_rows',
 'max_seq_items',
 'memory_usage',
 'multi_sparse',
 'notebook_repr_html',
 'pprint_nest_depth',
 'precision',
 'show_dimensions',
 'unicode',
 'width']

### Getting option values
All of the above are attributes that hold a scalar value. Let's output some of the default option values:

In [15]:
pd.options.display.max_columns

20

In [16]:
pd.options.display.max_rows

60

In [17]:
pd.options.display.max_colwidth

50

### Setting a new option value
To set a new option value, assign a number value to it like you do any other variable. Let's change the maximum number of columns to 40 so that we can see every column in the movie dataset.

In [18]:
pd.options.display.max_columns = 40

In [19]:
movie.head()

,year,color,content_rating,duration,director_name,director_fb,actor1,actor1_fb,actor2,actor2_fb,actor3,actor3_fb,gross,genres,num_reviews,num_voted_users,plot_keywords,language,country,budget,imdb_score
title,,,,,,,,,,,,,,,,,,,,,
Avatar,2009.0,Color,PG-13,178.0,James Cameron,0.0,CCH Pounder,1000.0,Joel David Moore,936.0,Wes Studi,855.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,723.0,886204,avatar|future|marine|native|paraplegic,English,USA,237000000.0,7.9
Pirates of the Caribbean: At World's End,2007.0,Color,PG-13,169.0,Gore Verbinski,563.0,Johnny Depp,40000.0,Orlando Bloom,5000.0,Jack Davenport,1000.0,309404152.0,Action|Adventure|Fantasy,302.0,471220,goddess|marriage ceremony|marriage proposal|pi...,English,USA,300000000.0,7.1
Spectre,2015.0,Color,PG-13,148.0,Sam Mendes,0.0,Christoph Waltz,11000.0,Rory Kinnear,393.0,Stephanie Sigman,161.0,200074175.0,Action|Adventure|Thriller,602.0,275868,bomb|espionage|sequel|spy|terrorist,English,UK,245000000.0,6.8
The Dark Knight Rises,2012.0,Color,PG-13,164.0,Christopher Nolan,22000.0,Tom Hardy,27000.0,Christian Bale,23000.0,Joseph Gordon-Levitt,23000.0,448130642.0,Action|Thriller,813.0,1144337,deception|imprisonment|lawlessness|police offi...,English,USA,250000000.0,8.5
Star Wars: Episode VII - The Force Awakens,NaN,NaN,NaN,NaN,Doug Walker,131.0,Doug Walker,131.0,Rob Walker,12.0,NaN,NaN,NaN,Documentary,NaN,8,NaN,NaN,NaN,NaN,7.1

# Exercises
For the following exercises, make sure to use the movie dataset with **`title`** set as the index. It's good practice to shorten your output with the **`head`** method.

### Problem 1
<span  style="color:green; font-size:16px">Select the column with the director's name as a Series</span>

In [ ]:
# your code here

### Problem 2
<span  style="color:green; font-size:16px">Select the column with the director's name and number of Facebook likes.</span>

In [ ]:
# your code here

# More questions
* Select a single column as a DataFrame and not a Series
* Look in the data folder and read in some of the other dataset. Select some columns from them.